Repository uktrade/data-hub-frontend, pull requests merged in 2018-07, with the labels that each got.

#1489 Hide "Add Investment project" button for archived companies
  src/apps/companies/controllers/investments.js
  test/acceptance/features/companies/collection.feature
  test/acceptance/features/contacts/collection.feature
  test/acceptance/features/investment-projects/create.feature
  test/acceptance/features/step_definitions/common.js
  test/acceptance/features/step_definitions/list.js
  test/acceptance/fixtures.js
Labels: enhancement

#1500 Acceptance test filter race condition
  test/acceptance/features/companies/collection.feature
  test/acceptance/features/contacts/collection.feature
Labels: bug

#1498 Warning and hide add attendee for disabled event
  src/apps/events/attendees/controllers/list.js
  src/apps/events/attendees/views/list.njk
  src/apps/events/transformers.js
  src/apps/events/views/_layout.njk
  src/apps/events/views/details.njk
  test/acceptance/features/events/attendees.feature
  test/acceptance/features/events/collection.feature
  test/acceptance/features/events/details.feature
  test/acceptance/features/events/step_definitions/collections.js
  test/acceptance/features/step_definitions/message.js
  test/acceptance/fixtures.js
  test/acceptance/pages/message.js
  test/unit/apps/events/attendees/controllers/list.test.js
  test/unit/apps/events/transformers.test.js
Labels: WIP

#1483 Refactor get collection middleware for contacts
  src/apps/companies/controllers/subsidiaries.js
  src/apps/companies/middleware/collection.js
  src/apps/contacts/middleware/collection.js
  src/apps/contacts/router.js
  src/apps/events/attendees/controllers/find.js
  src/apps/events/middleware/collection.js
  src/apps/interactions/middleware/collection.js
  src/apps/investment-projects/controllers/associated.js
  src/apps/investment-projects/controllers/create/equity-source.js
  src/apps/investment-projects/controllers/ukcompany.js
  src/apps/investment-projects/middleware/collection.js
  src/apps/omis/apps/create/controllers/company.js
  src/apps/omis/apps/list/middleware.js
  src/apps/omis/apps/reconciliation/middleware.js
  src/apps/propositions/middleware/collection.js
  src/apps/search/controllers.js
  src/modules/api/transformers/api-response-to-collection.js
  src/modules/api/transformers/index.js
  src/modules/permissions/filters.js
  src/modules/search/builders/index.js
  src/modules/search/builders/search-aggregation.js
  src/modules/search/middleware/collection.js
  src/modules/search/services.js
  src/modules/search/transformers/api-response-to-search-collection.js
  src/modules/search/transformers/index.js
  test/unit/apps/investment-projects/controllers/ukcompany.test.js
  test/unit/modules/search/builders/search-aggregation.test.js
  test/unit/modules/search/transformers/api-response-to-search-collection.test.js
Labels: component refactor

#1506 Move remaining usage of old permission filters
  src/apps/filters.js
  src/apps/middleware.js
  src/lib/options.js
  src/middleware/locals.js
  src/modules/permissions/filters.js
  test/unit/modules/permissions/filters.test.js
Labels: component refactor

#1507 Reuse getCollection for companies
  src/apps/companies/middleware/collection.js
  src/apps/companies/router.js
  test/unit/apps/companies/middleware/collection.test.js
  test/unit/modules/search/middleware/collection.test.js
Labels: component refactor

#1508 Reuse getCollection search function
  src/apps/components/router.js
  src/apps/events/middleware/collection.js
  src/apps/events/router.js
  src/apps/interactions/middleware/collection.js
  src/apps/investment-projects/middleware/collection.js
  src/apps/investment-projects/middleware/index.js
  src/apps/investment-projects/router.js
  src/apps/omis/apps/list/middleware.js
  src/apps/omis/apps/list/router.js
  src/apps/omis/apps/reconciliation/middleware.js
  src/apps/omis/apps/reconciliation/router.js
  src/apps/propositions/middleware/collection.js
  test/unit/apps/events/middleware/collection.test.js
  test/unit/apps/interactions/middleware/collection.test.js
  test/unit/apps/investment-projects/middleware/collection.test.js
  test/unit/apps/omis/apps/list/middleware.test.js
  test/unit/apps/omis/apps/reconciliation/middleware.test.js
  test/unit/apps/propositions/middleware/collection.test.js
Labels: component refactor
