Repository uktrade/data-hub-frontend, pull requests merged in 2018-06, with the labels that each got.

#1470 Add sector to filter options and list display for omis orders
  src/apps/omis/apps/list/controllers.js
  src/apps/omis/apps/list/macros.js
  src/apps/omis/apps/list/middleware.js
  src/apps/omis/transformers.js
  test/unit/apps/omis/apps/list/controllers.test.js
  test/unit/apps/omis/transformers.test.js
Labels: WIP

#1472 Bug/contact active filter
  assets/javascripts/lib/xhr.js
  src/apps/contacts/middleware/collection.js
  test/acceptance/features/contacts/collection.feature
  test/acceptance/features/step_definitions/list.js
  test/unit/apps/contacts/middleware/collection.test.js
Labels: bug

#1474 Add active/inactive filter to company
  src/apps/companies/constants.js
  src/apps/companies/macros/company-filters-fields.js
  src/apps/companies/middleware/collection.js
  src/apps/companies/router.js
  src/apps/contacts/constants.js
  src/apps/contacts/macros.js
  src/apps/contacts/middleware/collection.js
  src/apps/contacts/router.js
  src/middleware/collection.js
  test/acceptance/features/companies/collection.feature
  test/acceptance/features/companies/step_definitions/collection.js
  test/acceptance/pages/companies/list.js
  test/unit/apps/companies/middleware/collection.test.js
  test/unit/middleware/collection.test.js
Labels: enhancement

#1479 Refactor events and investment projects to use common getRequestBody
  src/apps/events/constants.js
  src/apps/events/middleware/collection.js
  src/apps/events/router.js
  src/apps/investment-projects/constants.js
  src/apps/investment-projects/middleware/collection.js
  src/apps/investment-projects/router.js
  test/unit/apps/events/middleware/collection.test.js
  test/unit/apps/investment-projects/middleware/collection.test.js
Labels: component refactor
