Repository uktrade/data-hub-frontend, pull requests merged in 2019-05, with the labels that each got.

#1927 Bug - filter active inactive advisers
  assets/javascripts/vue/typeahead.vue
  src/apps/adviser/repos.js
  src/apps/events/macros/event-filters-fields.js
  src/apps/interactions/macros/collection-filter-fields.js
  src/apps/investments/macros.js
  src/templates/_macros/form/typeahead.njk
  test/unit-client/assets/javascripts/vue/typeahead.test.js
  test/unit/apps/adviser/repos.test.js
  test/unit/apps/api/controllers/advisers.test.js
Labels: bug

#1921 Bug - missing contact adviser breaks interactions
  src/apps/interactions/transformers/interaction-to-list-item.js
  test/unit/apps/interactions/transformers/interaction-to-list-item.test.js
Labels: bug

#1939 Add nvmrc file to project
  .nvmrc
  README.md
Labels: enhancement

#1940 Revert country of origin filter to previous
  src/apps/investments/constants.js
  src/apps/investments/labels.js
  src/apps/investments/macros.js
Labels: bug

#1945 Add hint on project details page
  src/apps/investments/labels.js
  src/apps/investments/views/value-edit.njk
  test/acceptance/features/investment-projects/value-add.feature
Labels: enhancement

#1936 Create a large capital investor profile
  assets/javascripts/modules/add-items.js
  assets/javascripts/vue/typeahead.vue
  src/apps/api/controllers/options.js
  src/apps/components/views/form.njk
  src/apps/events/macros/event-edit-form.js
  src/apps/events/macros/event-filters-fields.js
  src/apps/interactions/macros/collection-filter-fields.js
  src/apps/interactions/macros/fields.js
  src/apps/investments/controllers/create/create-profile.js
  src/apps/investments/controllers/create/investor-profile.js
  src/apps/investments/macros.js
  src/apps/investments/router-create-investor.js
  src/apps/investments/router-opportunities.js
  src/apps/investments/router-profiles.js
  src/apps/investments/router-projects.js
  src/apps/investments/router.js
  src/apps/investments/routes/router-create-investor.js
  src/apps/investments/routes/router-opportunities.js
  src/apps/investments/routes/router-profiles.js
  src/apps/investments/views/create/investor-profile.njk
  src/lib/options.js
  src/modules/search/services.js
  src/templates/_macros/form/typeahead.njk
  test/functional/cypress/specs/investment-project/investment-profiles-create-profile-spec.js
  test/unit-client/assets/javascripts/modules/add-items.test.js
  test/unit-client/assets/javascripts/vue/typeahead.test.js
  test/unit/apps/api/controllers/options.test.js
  test/unit/apps/builders.test.js
  test/unit/apps/investment-projects/controllers/create/create-profile.test.js
  test/unit/modules/search/services.test.js
Labels: enhancement

#1951 Fix bug on conditional styles on typeaheads
  assets/javascripts/vue/typeahead.vue
  src/apps/investments/controllers/create/create-profile.js
  test/unit/apps/investment-projects/controllers/create/create-profile.test.js
Labels: Fix, bug

#1972 Refactor table assertion to reusable helper
  test/functional/cypress/helpers/key-value-table.js
  test/functional/cypress/selectors/key-value-table.js
  test/functional/cypress/specs/companies/business-details-spec.js
Labels: component refactor

#1977 Bug - Hold search term when choosing multiple options
  assets/javascripts/vue/typeahead.vue
Labels: bug
