Repository uktrade/data-hub-frontend, pull requests merged in 2019-07, with the labels that each got.

#2039 Upgrade Data Hub components to 0.3.5
  package.json
  test/functional/cypress/specs/companies/activity-feed-spec.js
  yarn.lock
Labels: depends on another

#2061 Bug - remove TAP from interaction form and sort service options
  src/apps/events/macros/event-edit-form.js
  src/apps/interactions/macros/interaction-form.js
  src/apps/interactions/services/interaction-options.js
  src/apps/interactions/transformers/interaction-to-options.js
  test/unit/apps/interactions/controllers/edit.interaction.test.js
Labels: bug

#2063 Bug - Remove auto select dropdown
  assets/javascripts/modules/conditional-subfields.js
Labels: bug

#2065 Guard against no service being submitted
  src/apps/interactions/transformers/interaction-form-body-to-api.js
  test/unit/apps/interactions/transformers/interaction-form-body-to-api.test.js
Labels: bug

#2049 prevent unvalidated redirect from '/:companyId/investments/'
  src/apps/companies/apps/investments/router.js
Labels: Fix

#2051 Replace req.originalUrl with res.locals.ORIGINAL_URL in documents upload middleware
  src/apps/documents/middleware/upload.js
Labels: Fix

#2052 Bugfix/prevet unvalidated redirect from omis controller edit lead assignee
  src/apps/omis/apps/edit/controllers/edit-lead-assignee.js
Labels: Fix

#2048 Delete duplicate operand companyName in interaction fields macro
  src/apps/interactions/macros/fields.js
Labels: Fix

#2046 Fix unvalidated dynamic method call in interactions and use 'kind' of interaction from the database where possible. Edit existing and add new tests.
  src/apps/interactions/controllers/edit.js
  src/apps/interactions/transformers/interaction-response-to-form.js
  test/unit/apps/interactions/controllers/edit.interaction.test.js
  test/unit/apps/interactions/transformers/interaction-response-to-form.test.js
Labels: Fix
