Repository uktrade/data-hub-frontend, pull requests merged in 2019-03, with the labels that each got.

#1781 Refactor companies subsidiaries tests
  test/unit/apps/companies/controllers/subsidiaries.test.js
Labels: component refactor

#1789 Fix proposition download link
  src/apps/documents/transformers.js
  src/templates/_components/key-value-table.njk
  test/unit/apps/documents/transformers.test.js
  test/unit/apps/propositions/transformers.test.js
  test/unit/components/key-value-table.test.js
  test/unit/data/documents/files-response.json
Labels: bug

#1787 Add companies-new-layout flag check for Data Hub company interactions
  src/apps/companies/middleware/interactions.js
  test/unit/apps/companies/middleware/interactions.test.js
Labels: depends on another

#1816 Reference correct template block
  src/apps/companies/views/exports-edit.njk
  test/functional/cypress/specs/interaction/add-interaction-spec.js
Labels: bug

#1835 Bug - Remove Vue class as it swallows click events
  src/apps/events/macros/event-edit-form.js
Labels: bug

#1849 Fix two bugs when going through add company flow
  src/apps/companies/controllers/add.js
  src/apps/companies/views/add-step-2.njk
  src/apps/companies/views/edit.njk
  test/unit/apps/companies/controllers/add.test.js
Labels: bug
