Repository uktrade/data-hub-frontend, pull requests merged in 2020-10, with the labels that each got.

#3023 Rollback image-webpack-loader update
  package-lock.json
  package.json
Labels: bug, dependencies

#3028 Update Storybook config to work with version 6+
  .storybook/main.js
  .storybook/preview.js
Labels: Fix

#2905 Reactify investment projects collection list
  package-lock.json
  src/apps/companies/apps/dnb-hierarchy/client/DnbHierarchy.jsx
  src/apps/companies/apps/exports/client/ExportWins/index.jsx
  src/apps/companies/apps/exports/client/ExportWins/reducer.js
  src/apps/companies/apps/exports/client/ExportsHistory/index.jsx
  src/apps/companies/apps/exports/client/ExportsHistory/reducer.js
  src/apps/investments/client/LargeCapitalProfileCollection.jsx
  src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
  src/apps/investments/client/profiles/reducer.js
  src/apps/investments/client/profiles/state.js
  src/apps/investments/client/profiles/tasks.js
  src/apps/investments/client/projects/ProjectsCollection.jsx
  src/apps/investments/client/projects/labels.js
  src/apps/investments/client/projects/reducer.js
  src/apps/investments/client/projects/state.js
  src/apps/investments/client/projects/tasks.js
  src/apps/investments/client/state.js
  src/apps/investments/controllers/__test__/projects.test.js
  src/apps/investments/controllers/projects.js
  src/apps/investments/router-projects.js
  src/apps/investments/transformers/__test__/collection.test.js
  src/apps/investments/transformers/collection.js
  src/apps/investments/views/projects.njk
  src/apps/search/__test__/controllers.test.js
  src/client/actions.js
  src/client/components/CollectionList/CollectionDownload.jsx
  src/client/components/CollectionList/CollectionFilters.jsx
  src/client/components/CollectionList/CollectionHeader.jsx
  src/client/components/CollectionList/CollectionHeaderRow.jsx
  src/client/components/CollectionList/CollectionItem.jsx
  src/client/components/CollectionList/CollectionSort.jsx
  src/client/components/CollectionList/constants.js
  src/client/components/CollectionList/index.jsx
  src/client/components/FilteredCollectionList/index.jsx
  src/client/components/Filters/elements/FilterAdvisersTypeahead/index.jsx
  src/client/components/Footer/index.jsx
  src/client/components/Pagination/index.jsx
  src/client/components/RoutedPagination/index.jsx
  src/client/components/RoutedSelect/index.jsx
  src/client/components/ToggleSection/assets/search-gov.uk.svg
  src/client/components/ToggleSection/index.jsx
  src/client/components/index.jsx
  src/client/index.jsx
  src/client/provider.jsx
  src/middleware/api-proxy.js
  test/end-to-end/cypress/specs/DA/collection-spec.js
  test/end-to-end/cypress/specs/DIT/collection-spec.js
  test/end-to-end/cypress/specs/LEP/collection-spec.js
  test/functional/cypress/specs/investments/collection-spec.js
  test/functional/cypress/specs/investments/filter-spec.js
  test/functional/cypress/specs/investments/investment-profiles-spec.js
  test/selectors/company/export.js
  test/visual/specs/data-hub-pages-spec.js
Labels: Do Not Merge
