Repository uktrade/data-hub-frontend, pull requests merged in 2022-03, with the labels that each got.

#4414 Delete vue package and obvious assets
  assets/javascripts/app-vue.js
  assets/javascripts/modules/add-items.js
  assets/javascripts/vue/filters.js
  assets/javascripts/vue/typeahead.vue
  assets/stylesheets/application.scss
  package-lock.json
  package.json
  src/templates/_macros/form/add-another.njk
  test/functional/cypress/specs/companies/referrals/referral-help-spec.js
  test/unit-client/assets/javascripts/modules/add-items.test.js
  test/unit-client/assets/javascripts/vue/filters.test.js
  test/unit-client/assets/javascripts/vue/typeahead.test.js
  webpack.config.js
Labels: WIP

#4417 Cleanup unused and legacy code
  assets/javascripts/lib/helpers.js
  scripts/fetch-trello-numbers.sh
  scripts/trello-description.py
  src/apps/companies/controllers/__test__/contacts.test.js
  src/apps/companies/controllers/list.js
  src/apps/companies/macros/company-filters-fields.js
  src/apps/companies/macros/index.js
  src/apps/contacts/macros.js
  src/apps/interactions/controllers/__test__/list.test.js
  src/apps/interactions/controllers/list.js
  src/apps/interactions/macros/collection-filter-fields.js
  src/apps/interactions/macros/index.js
  src/apps/investments/macros.js
  src/apps/omis/apps/edit/fields.js
  src/apps/omis/apps/list/macros.js
  src/apps/propositions/controllers/list.js
  src/templates/_layouts/template.njk
  src/templates/_macros/collection/__test__/collection-filters.test.js
  src/templates/_macros/collection/collection-filters.njk
  src/templates/_macros/form.njk
  src/templates/_macros/form/typeahead.njk
  test/unit-client/assets/javascripts/lib/helpers.test.js
  test/unit-client/mocha.opts
  test/unit-client/prettier-fixer.js
Labels: WIP, Do Not Merge

#4449 Add ContactInformation component to Interaction Form
  src/apps/interactions/apps/details-form/client/StepInteractionDetails.jsx
  test/functional/cypress/specs/interaction/details-form-spec.js
Labels: Do Not Merge

#4451 Small design amendements to the Contacts form
  src/client/components/ContactForm/index.jsx
  src/client/components/Resource/__stories__/tasks.js
  test/end-to-end/cypress/specs/DIT/contacts-spec.js
  test/end-to-end/cypress/support/user-actions/contacts.js
  test/functional/cypress/specs/companies/referrals/send-referral-spec.js
  test/functional/cypress/specs/contacts/create-and-edit.jsx
  test/functional/cypress/specs/interaction/details-form-spec.js
Labels: Do Not Merge
