Repository uktrade/data-hub-frontend, pull requests merged in 2024-10, with the labels that each got.

#7217 CLS2-906: Add Investment Project button in EYB Lead details page
  Makefile
  src/client/components/Layout/EYBLeadLayout.jsx
  test/functional/cypress/specs/investments/eyb-lead-details-spec.js
  test/functional/cypress/specs/investments/project-add-investment-spec.js
Labels: enhancement

#7219 Dependencies 8th Oct 2024
  Dockerfile
  Dockerfile.dependencies
  docs/Docker.md
  package-lock.json
  package.json
  test/sandbox/package-lock.json
  test/sandbox/package.json
Labels: dependencies

#7241 CLS2-1000: Handle EYB leads that have no company gracefully
  src/client/components/Layout/EYBLeadLayout.jsx
  src/client/modules/Investments/EYBLeads/EYBLeadDetails.jsx
  src/client/modules/Investments/EYBLeads/EYBLeadName.jsx
  src/client/modules/Investments/EYBLeads/tasks.js
  src/client/modules/Investments/EYBLeads/transformers.js
  test/functional/cypress/specs/investments/eyb-lead-details-spec.js
  test/functional/cypress/specs/investments/eyb-leads-spec.js
Labels: enhancement

#7255 Dependencies 24th Oct 2024
  package-lock.json
  package.json
Labels: dependencies

#7238 CLS2-994 Field names updates
  src/client/modules/Investments/EYBLeads/EYBLeadDetails.jsx
  src/client/modules/Investments/EYBLeads/transformers.js
  test/api-schema.json
  test/functional/cypress/fakers/eyb-leads.js
  test/functional/cypress/specs/investments/eyb-leads-spec.js
  test/sandbox/fixtures/v4/investment/eyb-lead-list.json
Labels: Fix

#7268 Dependencies 28th Oct 2024
  package-lock.json
  package.json
  test/sandbox/package-lock.json
  test/sandbox/package.json
Labels: dependencies

#7274 CLS2-1016: Company website is not a relative link
  src/client/modules/Investments/EYBLeads/EYBLeadDetails.jsx
  test/functional/cypress/specs/investments/eyb-lead-details-spec.js
Labels: bug

#7276 CLS2-1015: Conditionally hide/show "Add Investment Project" button from EYB Lead
  src/client/components/Layout/EYBLeadLayout.jsx
  test/functional/cypress/fakers/eyb-leads.js
  test/functional/cypress/specs/investments/eyb-lead-details-spec.js
Labels: enhancement
